# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/volcanoPlot',
                'doc_host': 'https://avivleemann.github.io',
                'git_url': 'https://github.com/avivleemann/volcanoPlot',
                'lib_path': 'volcanoPlot'},
  'syms': {'volcanoPlot.core': {'volcanoPlot.core.foo': ('core.html#foo', 'volcanoPlot/core.py')}}}
