# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_volcanoPlot.ipynb.

# %% auto 0
__all__ = ['df', 'assign_sig', 'VolcanoPlot']

# %% ../nbs/00_volcanoPlot.ipynb 5
def assign_sig(p_value : int, log2FC: int, pvalue_cutoff: float=0.05 , log2FC_cutoff: int=2 ) -> str:
   '''
   assigns a gene to a category based on the p_value and log2FC. 
   lables: p_value and log2FC, p_value, log2FC or non-sig.
   p_value and log2FC: abs(log2FC) > log2FC_cutoff and p_value < pvalue_cutoff.
   p_value: abs(log2FC) <= log2FC_cutoff and p_value < pvalue_cutoff.
   log2FC: abs(log2FC) > log2FC_cutoff and p_value >= pvalue_cutoff.
   parameters:
   - p_value: p_value.
   - log2FC: log2fC.
   - pvalue_cutoff: p_value cutoff.
   - log2FC_cutoff: log2fC cutoff.
   
   returns:
   label: str 
   '''
   if p_value < pvalue_cutoff and abs(log2FC) > log2FC_cutoff :
      return 'log2FC and p_value'
   elif p_value < pvalue_cutoff and   abs(log2FC)  <= log2FC_cutoff: 
      return 'p_value'
   elif p_value >= pvalue_cutoff and  abs(log2FC)  > log2FC_cutoff:
      return 'log2FC'
   else:
      return 'non-sig'

# %% ../nbs/00_volcanoPlot.ipynb 7
def VolcanoPlot(df: Type[pd.DataFrame], x: str = 'log2FC', y: str = 'log10p', 
                xline_color: str = 'grey', yline_color: str = 'grey', line_style: str = '--',
                loc: str = 'upper left', bbox_to_anchor: Optional[tuple] = (0.3, 1),
                figsize: tuple = (8, 8), axline: float = 2, title: str = "Volcano Plot",
                top_n: int = 10, save_path: Optional[str] = None,dpi: int=300 , **kwargs) -> None:
    """
    Generate a volcano plot to visualize differential gene expression.

    Parameters:
    - df: pandas DataFrame containing the data.
    - x: column name for the x-axis.
    - y: column name for the y-axis.
    - xline_color: color of the vertical lines.
    - yline_color: color of the horizontal line.
    - line_style: style of the lines.
    - loc: location of the legend (e.g., 'upper left', 'lower right', 'center', etc.).
    - bbox_to_anchor: anchor point of the legend.
    - figsize: size of the figure.
    - axline: x-axis value for the vertical lines.
    - title: title of the plot.
    - top_n: number of top genes to label.
    - save_path: path to save the plot as an image file (optional).
    - **kwargs: additional keyword arguments for scatter plot customization.

    Returns:
    - None
    """
    if 'assign_sig' not in df.columns:
        df['assign_sig'] = df.apply(lambda row: assign_sig(row['p_value'], row['log2FC']), axis=1)
    else:
        df = df.assign( assign_sig_old = df['assign_sig'],
                        assign_sig = df.apply(lambda row: assign_sig(row['p_value'], row['log2FC']), axis=1))

    plt.figure(figsize=figsize)
    plt.scatter(x=df[x], y=df[y], s=1, label="Not significant", color="grey", alpha=0.5, **kwargs)

    lfc2_df = df[df.assign_sig == 'log2FC'].copy()
    pvalue_df = df[df.assign_sig == 'p_value'].copy()
    both_df = df[df.assign_sig == 'log2FC and p_value'].copy()

    plt.scatter(x=pvalue_df[x], y=pvalue_df[y], s=3, label="p-value", color="blue", marker="o", alpha=0.5, **kwargs)
    plt.scatter(x=lfc2_df[x], y=lfc2_df[y], s=3, label="log2FC", color="green", marker="o", alpha=0.5, **kwargs)
    plt.scatter(x=both_df[x], y=both_df[y], s=3, label='log2FC and p-value', color="red", marker="o", alpha=0.5, **kwargs)

    texts = []
    top_n_indices = both_df[y].nlargest(top_n).index
    for i, index in enumerate(top_n_indices):
        texts.append(plt.text(both_df.loc[index, x], both_df.loc[index, y], index, fontsize=8))

    adjust_text(texts, arrowprops=dict(arrowstyle='->', color='black', lw=0.8), expand_points=(1.5, 1.5), expand_text=(1.5, 1.5))

    plt.xlabel(x)
    plt.ylabel(y)
    plt.title(title)
    plt.axvline(-axline, color=xline_color, linestyle=line_style)
    plt.axvline(axline, color=xline_color, linestyle=line_style)
    plt.axhline(-np.log10(0.05), color=yline_color, linestyle=line_style)
    plt.legend(loc=loc, bbox_to_anchor=bbox_to_anchor)

    if save_path:
        plt.savefig(save_path, dpi=dpi)

    plt.show()

# %% ../nbs/00_volcanoPlot.ipynb 9
df = pd.read_csv(Path().cwd() / 'res_example.csv')
df.head()
